'use client';
import { create } from 'zustand';

export const translations = {
  en: {
    // Branding
    appName: 'Deshmukh Electronics',
    appSubtitle: 'Warehouse & Team App',
    
    // Auth & Navigation
    login: 'Sign In',
    welcomeBack: 'Welcome back',
    signInSubtitle: 'Sign in to your account to continue',
    emailAddress: 'Email Address',
    password: 'Password',
    signingIn: 'Signing in...',
    quickDemoLogin: 'Quick Demo Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    products: 'Products',
    qrCodes: 'QR Codes',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    transfers: 'Transfers',
    transfer: 'Transfer',
    warehouses: 'Warehouses',
    adjustments: 'Adjustments',
    adjustment: 'Adjustment',
    damagedStock: 'Damaged Stock',
    damaged: 'Damaged',
    returns: 'Returns',
    return: 'Return',
    audits: 'Audits',
    suppliers: 'Suppliers',
    customers: 'Customers',
    attendance: 'Attendance',
    salary: 'Salary Slips',
    reports: 'Reports',
    usersRoles: 'Users & Roles',
    notifications: 'Notifications',
    profile: 'My Profile',
    activity: 'Activity',
    timeline: 'Timeline & Goals',
    goals: 'Dispatch Goals',
    assignGoal: 'Assign Goal',
    readyToDispatch: 'Ready to Dispatch',
    dispatched: 'Dispatched',
    delivered: 'Delivered',
    deadline: 'Deadline',
    urgentDispatch: 'Urgent Dispatch',
    dueSoon: 'Due Soon',
    overdue: 'Overdue',
    markReady: 'Mark Ready',
    markDispatched: 'Mark Dispatched',
    markDelivered: 'Mark Delivered',
    assignedWorkers: 'Assigned Workers',

    // Worker Home & Scan Flow
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    notPunchedIn: 'Not Punched In',
    tapToPunchIn: 'Tap to punch in for today',
    punchedIn: 'Punched In',
    scanQRCode: 'Scan QR Code',
    scanPrompt: 'Scan product to perform action',
    quickActions: 'Quick Actions',
    myRecentActivity: 'My Recent Activity',
    seeAll: 'See all',
    scanStep: 'Scan',
    identifyStep: 'Identify',
    actionStep: 'Action',
    quantityStep: 'Quantity',
    confirmStep: 'Confirm',
    manualEntry: 'Manual Entry',
    useCamera: 'Use Camera',
    findProduct: 'Find Product',
    productFound: 'Product Found',
    currentStock: 'Current Stock',
    availableStock: 'Available Stock',
    selectAction: 'Select Action',
    enterDetails: 'Enter Details',
    reason: 'Reason',
    confirmAction: 'Confirm Action',
    actionSuccess: 'Movement recorded successfully!',
    scanAnother: 'Scan Another',
    backToHome: 'Back to Home',
    insufficientStock: 'Insufficient stock available!',

    // Dashboard & KPIs
    totalProducts: 'Total Products',
    totalStock: 'Total Stock',
    todayIncoming: "Today's Incoming",
    todayOutgoing: "Today's Outgoing",
    lowStockItems: 'Low Stock Items',
    pendingApprovals: 'Pending Approvals',
    activeWarehouses: 'Active Warehouses',
    stockMovement7Days: 'Stock Movement (7 Days)',
    stockByCategory: 'Stock by Category',
    warehouseDistribution: 'Warehouse Stock Distribution',
    recentMovements: 'Recent Stock Movements',

    // Attendance
    punchIn: 'Punch In',
    punchOut: 'Punch Out',
    totalHours: 'Total Hours',
    thisMonthSummary: 'This Month Summary',
    daysPresent: 'Days Present',
    lateArrivals: 'Late Arrivals',
    absences: 'Absences',
    teamAttendance: 'Team Attendance',
    myAttendance: 'My Attendance',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    approve: 'Approve',
    reject: 'Reject',
    exportCSV: 'Export CSV',
    print: 'Print',
    status: 'Status',
    date: 'Date',
    quantity: 'Quantity',
    warehouse: 'Warehouse',
    supplier: 'Supplier',
    customer: 'Customer',
  },

  mr: {
    // Marathi (मराठी)
    appName: 'देशमुख इलेक्ट्रॉनिक्स',
    appSubtitle: 'वेअरहाऊस आणि संघ ॲप',
    
    // Auth & Navigation
    login: 'साइन इन करा',
    welcomeBack: 'पुन्हा स्वागत आहे',
    signInSubtitle: 'पुढे जाण्यासाठी आपल्या खात्यात साइन इन करा',
    emailAddress: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    signingIn: 'साइन इन होत आहे...',
    quickDemoLogin: 'झटपट डेमो लॉगिन',
    logout: 'बाहेर पडा',
    dashboard: 'डॅशबोर्ड',
    inventory: 'इन्व्हेंटरी',
    products: 'उत्पादने',
    qrCodes: 'QR कोड',
    incoming: 'आवक माल',
    outgoing: 'जावक माल',
    transfers: 'हस्तांतरण',
    transfer: 'हस्तांतरण',
    warehouses: 'गोदामे',
    adjustments: 'साठा समायोजन',
    adjustment: 'समायोजन',
    damagedStock: 'खराब साठा',
    damaged: 'खराब माल',
    returns: 'परतावा (रिटर्न)',
    return: 'परतावा',
    audits: 'तपासणी (ऑडिट)',
    suppliers: 'पुरवठादार',
    customers: 'ग्राहक',
    attendance: 'हजेरी',
    salary: 'पगार स्लिप्स',
    reports: 'अहवाल (रिपोर्ट्स)',
    usersRoles: 'वापरकर्ते आणि भूमिका',
    notifications: 'सूचना',
    profile: 'माझे प्रोफाइल',
    activity: 'हालचाली',
    timeline: 'टाइमलाइन आणि उद्दिष्टे',
    goals: 'डिस्पॅच उद्दिष्टे',
    assignGoal: 'उद्दिष्ट द्या (Assign Goal)',
    readyToDispatch: 'डिस्पॅचसाठी तयार',
    dispatched: 'पाठवले (Dispatched)',
    delivered: 'वितरित झाले (Delivered)',
    deadline: 'अंतिम मुदत (Deadline)',
    urgentDispatch: 'तातडीचे डिस्पॅच',
    dueSoon: 'लवकरच मुदत संपत आहे',
    overdue: 'मुदत संपली (Overdue)',
    markReady: 'तयार म्हणून नोंदवा',
    markDispatched: 'पाठवले म्हणून नोंदवा',
    markDelivered: 'वितरित झाले म्हणून नोंदवा',
    assignedWorkers: 'नेमलेले कर्मचारी',

    // Worker Home & Scan Flow
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    notPunchedIn: 'हजेरी लागलेली नाही',
    tapToPunchIn: 'आजची हजेरी लावण्यासाठी टॅप करा',
    punchedIn: 'हजेरी नोंदवली',
    scanQRCode: 'QR कोड स्कॅन करा',
    scanPrompt: 'कृती करण्यासाठी उत्पादन स्कॅन करा',
    quickActions: 'जलद कृती',
    myRecentActivity: 'माझ्या अलीकडील हालचाली',
    seeAll: 'सर्व पहा',
    scanStep: 'स्कॅन',
    identifyStep: 'ओळख',
    actionStep: 'कृती',
    quantityStep: 'प्रमाण',
    confirmStep: 'खात्री करा',
    manualEntry: 'मॅन्युअल नोंद',
    useCamera: 'कॅमेरा वापरा',
    findProduct: 'उत्पादन शोधा',
    productFound: 'उत्पादन सापडले',
    currentStock: 'सध्याचा साठा',
    availableStock: 'उपलब्ध साठा',
    selectAction: 'कृती निवडा',
    enterDetails: 'तपशील भरा',
    reason: 'कारण',
    confirmAction: 'कृतीची खात्री करा',
    actionSuccess: 'नोंद यशस्वीरीत्या पूर्ण झाली!',
    scanAnother: 'दुसरे स्कॅन करा',
    backToHome: 'मुख्य पृष्ठावर जा',
    insufficientStock: 'गोदामात पुरेसा साठा उपलब्ध नाही!',

    // Dashboard & KPIs
    totalProducts: 'एकूण उत्पादने',
    totalStock: 'एकूण साठा',
    todayIncoming: 'आजची आवक',
    todayOutgoing: 'आजची जावक',
    lowStockItems: 'कमी साठ्यातील वस्तू',
    pendingApprovals: 'प्रलंबित मंजुरी',
    activeWarehouses: 'सक्रिय गोदामे',
    stockMovement7Days: '७ दिवसांतील हालचाली',
    stockByCategory: 'विभागानुसार साठा',
    warehouseDistribution: 'गोदामनिहाय साठा वितरण',
    recentMovements: 'अलीकडील साठ्याच्या हालचाली',

    // Attendance
    punchIn: 'पंच इन करा',
    punchOut: 'पंच आउट करा',
    totalHours: 'एकूण तास',
    thisMonthSummary: 'या महिन्याचा गोषवारा',
    daysPresent: 'उपस्थित दिवस',
    lateArrivals: 'उशिरा आगमन',
    absences: 'गैरहजर दिवस',
    teamAttendance: 'संघाची हजेरी',
    myAttendance: 'माझी हजेरी',

    // Common
    save: 'जतन करा',
    cancel: 'रद्द करा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    approve: 'मंजूर करा',
    reject: 'नाकारा',
    exportCSV: 'CSV डाउनलोड करा',
    print: 'प्रिंट करा',
    status: 'स्थिती',
    date: 'तारीख',
    quantity: 'प्रमाण',
    warehouse: 'गोदाम',
    supplier: 'पुरवठादार',
    customer: 'ग्राहक',
  },

  hi: {
    // Hindi (हिंदी)
    appName: 'देशमुख इलेक्ट्रॉनिक्स',
    appSubtitle: 'वेयरहाउस और टीम ऐप',
    
    // Auth & Navigation
    login: 'साइन इन करें',
    welcomeBack: 'वापसी पर स्वागत है',
    signInSubtitle: 'आगे बढ़ने के लिए अपने खाते में साइन इन करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    signingIn: 'साइन इन हो रहा है...',
    quickDemoLogin: 'त्वरित डेमो लॉगिन',
    logout: 'लॉग आउट',
    dashboard: 'डैशबोर्ड',
    inventory: 'इन्वेंट्री',
    products: 'उत्पाद',
    qrCodes: 'QR कोड',
    incoming: 'आवक माल',
    outgoing: 'जावक माल',
    transfers: 'स्थानांतरण',
    transfer: 'ट्रांसफर',
    warehouses: 'गोदाम (वेयरहाउस)',
    adjustments: 'स्टॉक समायोजन',
    adjustment: 'समायोजन',
    damagedStock: 'क्षतिग्रस्त स्टॉक',
    damaged: 'डैमेज्ड माल',
    returns: 'वापसी (रिटर्न)',
    return: 'रिटर्न',
    audits: 'ऑडिट / जांच',
    suppliers: 'आपूर्तिकर्ता',
    customers: 'ग्राहक',
    attendance: 'उपस्थिति (अटेंडेंस)',
    salary: 'वेतन पर्ची (सैलरी स्लिप)',
    reports: 'रिपोर्ट्स',
    usersRoles: 'उपयोगकर्ता और भूमिकाएं',
    notifications: 'सूचनाएं',
    profile: 'मेरी प्रोफाइल',
    activity: 'गतिविधि',
    timeline: 'टाइमलाइन और लक्ष्य',
    goals: 'डिस्पैच लक्ष्य',
    assignGoal: 'लक्ष्य सौंपें (Assign Goal)',
    readyToDispatch: 'डिस्पैच के लिए तैयार',
    dispatched: 'भेज दिया गया (Dispatched)',
    delivered: 'डिलीवर हुआ (Delivered)',
    deadline: 'अंतिम समय सीमा (Deadline)',
    urgentDispatch: 'अति आवश्यक डिस्पैच',
    dueSoon: 'शीघ्र देय',
    overdue: 'समय समाप्त (Overdue)',
    markReady: 'तैयार चिह्नित करें',
    markDispatched: 'डिस्पैच चिह्नित करें',
    markDelivered: 'डिलीवर चिह्नित करें',
    assignedWorkers: 'सौंपे गए कार्यकर्ता',

    // Worker Home & Scan Flow
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    notPunchedIn: 'उपस्थिति दर्ज नहीं है',
    tapToPunchIn: 'आज की उपस्थिति दर्ज करने के लिए टैप करें',
    punchedIn: 'उपस्थिति दर्ज हो गई',
    scanQRCode: 'QR कोड स्कैन करें',
    scanPrompt: 'कार्यवाही के लिए उत्पाद स्कैन करें',
    quickActions: 'त्वरित कार्य',
    myRecentActivity: 'मेरी हाल की गतिविधि',
    seeAll: 'सभी देखें',
    scanStep: 'स्कैन',
    identifyStep: 'पहचान',
    actionStep: 'कार्रवाई',
    quantityStep: 'मात्रा',
    confirmStep: 'पुष्टि करें',
    manualEntry: 'मैन्युअल प्रविष्टि',
    useCamera: 'कैमरा उपयोग करें',
    findProduct: 'उत्पाद खोजें',
    productFound: 'उत्पाद मिल गया',
    currentStock: 'वर्तमान स्टॉक',
    availableStock: 'उपलब्ध स्टॉक',
    selectAction: 'कार्रवाई चुनें',
    enterDetails: 'विवरण दर्ज करें',
    reason: 'कारण',
    confirmAction: 'कार्रवाई की पुष्टि करें',
    actionSuccess: 'प्रविष्टि सफलतापूर्वक दर्ज हो गई!',
    scanAnother: 'दूसरा स्कैन करें',
    backToHome: 'मुख्य पृष्ठ पर लौटें',
    insufficientStock: 'वेयरहाउस में पर्याप्त स्टॉक उपलब्ध नहीं है!',

    // Dashboard & KPIs
    totalProducts: 'कुल उत्पाद',
    totalStock: 'कुल स्टॉक',
    todayIncoming: 'आज की आवक',
    todayOutgoing: 'आज की जावक',
    lowStockItems: 'कम स्टॉक वाले आइटम',
    pendingApprovals: 'लंबित अनुमोदन',
    activeWarehouses: 'सक्रिय वेयरहाउस',
    stockMovement7Days: '7 दिनों का स्टॉक मूवमेंट',
    stockByCategory: 'श्रेणी अनुसार स्टॉक',
    warehouseDistribution: 'वेयरहाउस अनुसार स्टॉक वितरण',
    recentMovements: 'हाल के स्टॉक मूवमेंट',

    // Attendance
    punchIn: 'पंच इन करें',
    punchOut: 'पंच आउट करें',
    totalHours: 'कुल घंटे',
    thisMonthSummary: 'इस माह का सारांश',
    daysPresent: 'उपस्थित दिन',
    lateArrivals: 'देर से आगमन',
    absences: 'अनुपस्थित दिन',
    teamAttendance: 'टीम उपस्थिति',
    myAttendance: 'मेरी उपस्थिति',

    // Common
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    approve: 'स्वीकृत करें',
    reject: 'अस्वीकृत करें',
    exportCSV: 'CSV डाउनलोड करें',
    print: 'प्रिंट करें',
    status: 'स्थिति',
    date: 'दिनांक',
    quantity: 'मात्रा',
    warehouse: 'गोदाम',
    supplier: 'आपूर्तिकर्ता',
    customer: 'ग्राहक',
  },
};

export const useLanguageStore = create((set, get) => ({
  language: 'en',
  
  setLanguage: (lang) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('de_lang', lang);
    }
    set({ language: lang });
  },

  initializeLanguage: () => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('de_lang');
      if (saved && ['en', 'mr', 'hi'].includes(saved)) {
        set({ language: saved });
      }
    }
  },

  t: (key) => {
    const lang = get().language || 'en';
    const dict = translations[lang] || translations.en;
    return dict[key] || translations.en[key] || key;
  },
}));

export default useLanguageStore;
